default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.7.1'
    hooks:
      - id: prettier
        args: ['--cache', '--cache-strategy', 'metadata']
        additional_dependencies:
          - 'prettier@^2.7.1'
          - '@trivago/prettier-plugin-sort-imports@^3.2.0'
